CREATE TABLE IF NOT EXISTS profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  display_name VARCHAR(100) NOT NULL,
  headline VARCHAR(255) NOT NULL,
  bio TEXT NOT NULL,
  location VARCHAR(120) NOT NULL DEFAULT '',
  links JSON NOT NULL,
  now_items JSON NOT NULL,
  skills JSON NOT NULL,
  journey JSON NOT NULL,
  principles JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS categories (
  id VARCHAR(64) NOT NULL,
  slug VARCHAR(120) NOT NULL,
  name VARCHAR(120) NOT NULL,
  visibility ENUM('public', 'registered') NOT NULL DEFAULT 'public',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_categories_slug (slug),
  KEY idx_categories_visibility_sort (visibility, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS articles (
  id VARCHAR(64) NOT NULL,
  slug VARCHAR(160) NOT NULL,
  title VARCHAR(255) NOT NULL,
  subtitle VARCHAR(500) NOT NULL DEFAULT '',
  excerpt VARCHAR(800) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  category_id VARCHAR(64) NOT NULL,
  tags JSON NOT NULL,
  status ENUM('draft', 'published', 'scheduled', 'archived') NOT NULL DEFAULT 'draft',
  visibility ENUM('inherit', 'public', 'registered') NOT NULL DEFAULT 'inherit',
  published_at DATETIME(3) NULL,
  scheduled_at DATETIME(3) NULL,
  read_time VARCHAR(60) NOT NULL DEFAULT '',
  views VARCHAR(60) NOT NULL DEFAULT '',
  view_count BIGINT NOT NULL DEFAULT 0,
  cover_accent ENUM('sky', 'emerald', 'violet', 'amber') NOT NULL DEFAULT 'sky',
  cover_image_url VARCHAR(500) NULL,
  cover_alt VARCHAR(255) NOT NULL DEFAULT '',
  is_featured BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at DATETIME(3) NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uk_articles_slug (slug),
  KEY idx_articles_public_list (status, published_at, deleted_at),
  KEY idx_articles_category_status (category_id, status, published_at),
  KEY idx_articles_featured (is_featured, status, published_at),
  CONSTRAINT fk_articles_category FOREIGN KEY (category_id) REFERENCES categories(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO profiles (
  id,
  display_name,
  headline,
  bio,
  location,
  links,
  now_items,
  skills,
  journey,
  principles
) VALUES (
  1,
  'Arjun Dev',
  'Writing about backend systems, product engineering, and the quiet craft of building.',
  '我喜欢把复杂系统拆开看清楚，再用写作把这些理解沉淀下来。Fluxa 是我的个人博客系统，也是持续打磨工程能力的地方。',
  'Bengaluru, India',
  JSON_ARRAY(JSON_OBJECT('label', 'GitHub', 'href', 'https://github.com'), JSON_OBJECT('label', 'Email', 'href', 'mailto:hello@example.com')),
  JSON_ARRAY(
    JSON_OBJECT('title', 'Learning', 'status', 'In progress', 'text', 'Digging deeper into Go, system design, and distributed systems.', 'color', 'violet'),
    JSON_OBJECT('title', 'Building', 'status', 'In progress', 'text', 'Building Fluxa, a modern blog system to record ideas and share knowledge.', 'color', 'emerald'),
    JSON_OBJECT('title', 'Writing', 'status', 'Ongoing', 'text', 'Writing technical articles about backend, systems, and engineering growth.', 'color', 'blue'),
    JSON_OBJECT('title', 'Preparing', 'status', 'Ongoing', 'text', 'Preparing for internships and looking for opportunities to grow and contribute.', 'color', 'purple')
  ),
  JSON_ARRAY(
    JSON_OBJECT('group', 'Backend', 'items', JSON_ARRAY('Go', 'Java', 'Hertz', 'Kitex', 'GORM', 'Spring Boot')),
    JSON_OBJECT('group', 'Data & Cache', 'items', JSON_ARRAY('MySQL', 'Redis', 'MongoDB', 'PostgreSQL', 'Elasticsearch')),
    JSON_OBJECT('group', 'Messaging & Infra', 'items', JSON_ARRAY('Kafka', 'RabbitMQ', 'Docker', 'Nginx', 'Linux', 'Git')),
    JSON_OBJECT('group', 'Frontend', 'items', JSON_ARRAY('Next.js', 'React', 'TypeScript', 'Tailwind CSS', 'HeroUI')),
    JSON_OBJECT('group', 'AI & Tools', 'items', JSON_ARRAY('LLM API', 'Eino', 'Prompt Engineering', 'API Integration'))
  ),
  JSON_ARRAY(
    JSON_OBJECT('period', '2024', 'title', 'Start the Journey', 'description', 'Started learning backend development and built my first web backend.'),
    JSON_OBJECT('period', '2025.03', 'title', 'Go Deeper', 'description', 'Explored Go, microservices, and high-performance system design.'),
    JSON_OBJECT('period', '2025.08', 'title', 'Build & Ship', 'description', 'Built multiple projects including LiveLive, ALLesson, and more.'),
    JSON_OBJECT('period', '2026 · Now', 'title', 'Building Fluxa', 'description', 'Creating Fluxa and preparing for internships.')
  ),
  JSON_ARRAY(
    JSON_OBJECT('title', 'Build first, polish later.', 'description', '先让东西跑起来，再慢慢打磨细节。'),
    JSON_OBJECT('title', 'Write to think.', 'description', '用写作整理混乱的想法，让知识真正属于自己。'),
    JSON_OBJECT('title', 'Systems over snippets.', 'description', '不仅仅关注代码片段，更关心系统如何运行。'),
    JSON_OBJECT('title', 'Stay curious.', 'description', '对技术、工具和世界保持好奇和热情。')
  )
) ON DUPLICATE KEY UPDATE
  display_name = VALUES(display_name),
  headline = VALUES(headline),
  bio = VALUES(bio),
  location = VALUES(location),
  links = VALUES(links),
  now_items = VALUES(now_items),
  skills = VALUES(skills),
  journey = VALUES(journey),
  principles = VALUES(principles);

INSERT INTO categories (id, slug, name, visibility, sort_order) VALUES
  ('cat_systems', 'systems', 'Systems', 'public', 10),
  ('cat_go', 'go', 'Go', 'public', 20),
  ('cat_nextjs', 'nextjs', 'Next.js', 'public', 30),
  ('cat_observability', 'observability', 'Observability', 'public', 40),
  ('cat_ai', 'ai', 'AI', 'public', 50),
  ('cat_devops', 'devops', 'DevOps', 'public', 60),
  ('cat_notes', 'notes', 'Notes', 'registered', 70)
ON DUPLICATE KEY UPDATE
  slug = VALUES(slug),
  name = VALUES(name),
  visibility = VALUES(visibility),
  sort_order = VALUES(sort_order);

INSERT INTO articles (
  id,
  slug,
  title,
  subtitle,
  excerpt,
  content,
  category_id,
  tags,
  status,
  visibility,
  published_at,
  read_time,
  views,
  view_count,
  cover_accent,
  cover_alt,
  is_featured
) VALUES
  (
    'art_001',
    'designing-resilient-systems',
    'Designing Resilient Systems: Patterns That Scale',
    'A practical guide to building architecture that stays reliable, observable, and evolvable as your system and team grow.',
    'A practical look at boundaries, observability, and patterns that keep production systems understandable as they scale.',
    '# Why Resilience Matters\n\nSystems fail. Networks partition. Dependencies slow down. The only question is whether your system can adapt to those failures without cascading into an outage.\n\n> Resilience is not about preventing failure. It is about ensuring failure is contained, recovered from, and learned from.\n\n## Core Principles\n\n- **Isolate Failure:** Limit the blast radius so one failure does not bring down everything.\n- **Embrace Redundancy:** Add capacity across services and regions.\n- **Design for Recovery:** Build fast, safe recovery paths and test them.\n\n## Architectural Patterns\n\n### Circuit Breaker\n\nPrevent cascading failures by stopping calls to a failing dependency.\n\n```go\nif failureRate > threshold {\n    openCircuit()\n    return fallbackResponse()\n}\n```\n\n## Observability at Scale\n\nMetrics show trends, logs tell stories, and traces reveal the shape of user requests.\n\n## Key Takeaways\n\nResilience is a product quality, not just an infrastructure concern.',
    'cat_systems',
    JSON_ARRAY('Architecture', 'Reliability'),
    'published',
    'public',
    '2026-05-12 08:00:00.000',
    '12 min read',
    '3.2K views',
    3200,
    'sky',
    'Abstract systems illustration',
    TRUE
  ),
  (
    'art_002',
    'context-in-go-beyond-the-basics',
    'Context in Go: Beyond the Basics',
    'Explore context internals, cancellation patterns, and real-world pitfalls that can make or break services.',
    'Explore context internals, cancellation patterns, and real-world pitfalls that can make or break services.',
    '# Context in Go: Beyond the Basics\n\nExplore context internals, cancellation patterns, and real-world pitfalls.\n\n## Notes\n\nContext is the boundary between work that should continue and work that should stop.',
    'cat_go',
    JSON_ARRAY('Go', 'Backend', 'Concurrency'),
    'published',
    'public',
    '2026-05-10 08:00:00.000',
    '6 min read',
    '1.8K views',
    1800,
    'emerald',
    'Abstract Go article illustration',
    FALSE
  ),
  (
    'art_003',
    'advanced-nextjs-patterns-for-production',
    'Advanced Next.js: Patterns for Production',
    'Route groups, server components, cache strategy, and small composition choices for production apps.',
    'Route groups, server components, cache strategy, and the small composition choices that make larger apps easier to change.',
    '# Advanced Next.js: Patterns for Production\n\nRoute groups, server components, and cache strategy are architectural choices.\n\n## Notes\n\nKeep page files focused on data assembly and composition.',
    'cat_nextjs',
    JSON_ARRAY('Frontend', 'Next.js'),
    'published',
    'public',
    '2026-05-08 08:00:00.000',
    '9 min read',
    '2.6K views',
    2600,
    'violet',
    'Abstract frontend article illustration',
    FALSE
  ),
  (
    'art_004',
    'observability-101',
    'Observability 101: Logs, Metrics, Traces',
    'Build visibility into your systems with structured logs, meaningful metrics, and distributed tracing.',
    'Build visibility into your systems with structured logs, meaningful metrics, and distributed tracing.',
    '# Observability 101\n\nMetrics answer what is changing. Logs explain what happened. Traces show where time is spent.',
    'cat_observability',
    JSON_ARRAY('OpenTelemetry', 'SRE'),
    'published',
    'public',
    '2026-05-05 08:00:00.000',
    '8 min read',
    '2.1K views',
    2100,
    'sky',
    'Abstract observability article illustration',
    FALSE
  ),
  (
    'art_005',
    'building-llm-apps-that-do-not-break',
    'Building LLM Apps That Don''t Break',
    'What breaks in LLM apps first, how to design recovery paths, and where to keep humans in the loop.',
    'What breaks in LLM apps first, how to design recovery paths, and where to keep humans in the loop.',
    '# Building LLM Apps That Don''t Break\n\nLLM apps need recovery paths, evaluation, and human control points.',
    'cat_ai',
    JSON_ARRAY('AI', 'Product'),
    'published',
    'public',
    '2026-05-02 08:00:00.000',
    '10 min read',
    '1.5K views',
    1500,
    'amber',
    'Abstract AI article illustration',
    FALSE
  ),
  (
    'art_006',
    'deploying-distributed-systems-with-confidence',
    'Deploying Distributed Systems with Confidence',
    'Blue-green, canary, feature flags, and rollback habits for modern distributed systems.',
    'Blue-green, canary, feature flags, and rollback habits for modern distributed systems.',
    '# Deploying Distributed Systems with Confidence\n\nDeployments need progressive rollout, observability, and rollback paths.',
    'cat_devops',
    JSON_ARRAY('Kubernetes', 'Delivery'),
    'published',
    'public',
    '2026-04-30 08:00:00.000',
    '7 min read',
    '1.2K views',
    1200,
    'violet',
    'Abstract DevOps article illustration',
    FALSE
  )
ON DUPLICATE KEY UPDATE
  title = VALUES(title),
  subtitle = VALUES(subtitle),
  excerpt = VALUES(excerpt),
  content = VALUES(content),
  category_id = VALUES(category_id),
  tags = VALUES(tags),
  status = VALUES(status),
  visibility = VALUES(visibility),
  published_at = VALUES(published_at),
  read_time = VALUES(read_time),
  views = VALUES(views),
  view_count = VALUES(view_count),
  cover_accent = VALUES(cover_accent),
  cover_alt = VALUES(cover_alt),
  is_featured = VALUES(is_featured);
